#!/usr/bin/env python3
# make-hooklist.py -- every (class, selector) the tweak hooks with Logos (%hook ... %end), for the diagnostics on untested iPadOS versions
# (common/HookList.h, generated; re-run after adding or removing hooks). Names only.
import re, sys, os, glob
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
pairs = []
for path in sorted(glob.glob(os.path.join(root, '**', '*.x'), recursive=True)):
    if '/.theos/' in path or '/packages/' in path: continue
    cls = None
    for line in open(path, errors='replace'):
        m = re.match(r'\s*%hook\s+([A-Za-z_][A-Za-z0-9_]*)', line)
        if m: cls = m.group(1); continue
        if re.match(r'\s*%end\b', line): cls = None; continue
        if not cls: continue
        m = re.match(r'\s*([-+])\s*\([^)]*\)\s*(.*)', line)
        if not m: continue
        kind, rest = m.group(1), m.group(2)
        rest = rest.split('{')[0]
        parts = re.findall(r'([A-Za-z_][A-Za-z0-9_]*)\s*:', rest)
        sel = ''.join(p + ':' for p in parts) if parts else re.match(r'([A-Za-z_][A-Za-z0-9_]*)', rest).group(1)
        rel = os.path.relpath(path, root)
        pairs.append((cls, sel, kind, rel))
seen = set(); out = []
for p in pairs:
    if (p[0], p[1], p[2]) in seen: continue
    seen.add((p[0], p[1], p[2])); out.append(p)
with open(os.path.join(root, 'common', 'HookList.h'), 'w') as f:
    f.write('// HookList.h -- GENERATED by tools/make-hooklist.py (do not edit): every Logos hook (class, selector, +/-), for the untested-iPadOS\n')
    f.write('// diagnostics (common/Diag.h). Names only.\n#pragma once\n')
    f.write('static const char *const kMSBDHookList[][4] = {   // class, selector, +/-, source file\n')
    for c, s, k, r in out: f.write('    {"%s", "%s", "%s", "%s"},\n' % (c, s, k, r))
    f.write('};\n')
print(len(out), 'hooks')
